### ISSUE TITLE
Help converting json to html (Syntax Error) 

### ISSUE THREAD

**Issue by AndrasRichter** [andreax79/json2html-bookmarks#1]
Ask for help converting json to html.

I always get the message: **Syntax Error: Invalid Syntax.**

I did the following:

I loaded Python 2.7.18 (version: Windows x86 MSI installer) and then simplejson-3.17.0.win-amd64-py2.7.exe (295.0 kB, Windows Installer, Python version 2.7) Unfortunately i'm a layman, In this case.

Entered the following command:
python json2html.py bookmarks.samsung.json output.html
(have already tried bookmark samsung and bookmarks samsung, because of the point, but without success)

**Comment by andreax79** [comment]
Hi
Please try with Python 3.6, 3.7 or 3.8
or re-download json2html.py from there https://raw.githubusercontent.com/andreax79/json2html-bookmarks/master/json2html.py
